import fs from 'fs';
const f = 'c:\\Users\\Mitchell\\Downloads\\try\\test\\migration\\src\\pages\\Blog.jsx';
let s = '';
s += "import { useState } from 'react';\n";
s += "import { Link } from 'react-router-dom';\n";
s += "import Layout from '../layouts/LandingLayout';\n";
s += "import { Clock, ArrowRight, TrendingUp, Bookmark, ArrowLeft } from 'lucide-react';\n\n";
s += "const articles = [\n";
s += "  { id: 1, title: 'The Art of Intentional Matchmaking', excerpt: 'Approach your search with clarity and faith.', readTime: '5 min', category: 'Guidance', date: 'Aug 20, 2026', image: 'https://images.unsplash.com/photo-1516589178581-6cd7833ae3b2?auto=format&fit=crop&w=900&q=80', trending: true },\n";
s += "  { id: 2, title: 'Family Involvement in Your Search', excerpt: 'Balancing family input with compatibility.', readTime: '7 min', category: 'Family', date: 'Aug 15, 2026', image: 'https://images.unsplash.com/photo-1511895426328-dc8714191300?auto=format&fit=crop&w=900&q=80', trending: true },\n";
s += "  { id: 3, title: 'A Profile That Reflects Your Values', excerpt: 'Tips for an authentic profile.', readTime: '4 min', category: 'Tips', date: 'Aug 10, 2026', image: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?auto=format&fit=crop&w=900&q=80' },\n";
s += "  { id: 4, title: 'Privacy & Safety Online', excerpt: 'Protect your information.', readTime: '6 min', category: 'Safety', date: 'Aug 5, 2026', image: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=900&q=80' },\n";
s += "  { id: 5, title: 'Wali in Modern Matchmaking', excerpt: 'Guardianship for respectful introductions.', readTime: '5 min', category: 'Guardians', date: 'Jul 28, 2026', image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=900&q=80' },\n";
s += "  { id: 6, title: 'Red Flags and Green Flags', excerpt: 'What to look for early.', readTime: '8 min', category: 'Guidance', date: 'Jul 20, 2026', image: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?auto=format&fit=crop&w=900&q=80' },\n";
s += "  { id: 7, title: 'Cultural Compatibility', excerpt: 'Shared values and traditions.', readTime: '6 min', category: 'Guidance', date: 'Jul 12, 2026', image: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=900&q=80' },\n";
s += "  { id: 8, title: 'Preparing for First Meeting', excerpt: 'Chaperoned introduction advice.', readTime: '5 min', category: 'Tips', date: 'Jul 5, 2026', image: 'https://images.unsplash.com/photo-1516589178581-6cd7833ae3b2?auto=format&fit=crop&w=900&q=80' },\n";
s += "];\n\n";
s += "const categories = ['All', 'Guidance', 'Family', 'Tips', 'Safety', 'Guardians'];\n\n";
s += "function getBody(a) {\n";
s += "  return [\n";
s += "    a.title + ' matters deeply to anyone walking the path of intentional matchmaking.',\n";
s += "    'The foundation is clarity. Reflect on what you value before sending your first message.',\n";
s += "    'Complete every section of your profile. Honesty is attractive.',\n";
s += "    'Privacy is built in. Control who sees your photos.',\n";
s += "    'Take your time. The right person will respect your pace.',\n";
s += "    'May Allah put barakah in your search.',\n";
s += "  ].join('\\n\\n');\n";
s += "}\n\n";
fs.writeFileSync(f, s, 'utf8');
console.log('Blog.jsx part 1 done', s.length);

let t = '';
t += "export default function Blog() {\n";
t += "  const [activeCategory, setActiveCategory] = useState('All');\n";
t += "  const [reading, setReading] = useState(null);\n";
t += "  const [bookmarked, setBookmarked] = useState(new Set());\n";
t += "  const filtered = activeCategory === 'All' ? articles : articles.filter(a => a.category === activeCategory);\n";
t += "  const toggleBookmark = (id) => setBookmarked(prev => { const n = new Set(prev); if (n.has(id)) n.delete(id); else n.add(id); return n; });\n";
t += "  if (reading) {\n";
t += "    const body = getBody(reading);\n";
t += "    return (\n";
t += "      <Layout>\n";
t += "        <main className=\"max-w-3xl mx-auto px-4 sm:px-6 py-8 sm:py-12\">\n";
t += "          <button onClick={() => setReading(null)} className=\"inline-flex items-center gap-2 text-sm mb-6 group\" style={{ color: 'var(--color-ink-secondary)' }}>\n";
t += "            <ArrowLeft className=\"w-4 h-4 group-hover:-translate-x-1 transition-transform\" /> Back to articles\n";
t += "          </button>\n";
t += "          <span className=\"text-[11px] font-bold px-2.5 py-0.5 rounded-full\" style={{ color: 'var(--color-primary)', background: 'var(--color-primary-subtle)' }}>{reading.category}</span>\n";
t += "          <h1 style={{ fontSize: 'clamp(1.75rem,4vw,2.75rem)', fontWeight: 700, color: 'var(--color-ink)', lineHeight: 1.2, margin: '0.75rem 0 1rem' }}>{reading.title}</h1>\n";
t += "          <div className=\"flex items-center gap-4 mb-6\" style={{ color: 'var(--color-ink-faint)', fontSize: '0.8125rem' }}>\n";
t += "            <span className=\"flex items-center gap-1\"><Clock className=\"w-3 h-3\" /> {reading.readTime}</span>\n";
t += "            <span>{reading.date}</span>\n";
t += "          </div>\n";
t += "          <div className=\"rounded-2xl overflow-hidden mb-8\">\n";
t += "            <img src={reading.image} alt={reading.title} className=\"w-full h-64 sm:h-80 object-cover\" />\n";
t += "          </div>\n";
t += "          <div style={{ color: 'var(--color-ink-secondary)', lineHeight: 1.8, fontSize: '1rem' }}>\n";
t += "            {body.split('\\n\\n').map((p, i) => (<p key={i} style={{ marginBottom: '1.25rem' }}>{p}</p>))}\n";
t += "          </div>\n";
t += "          <div className=\"mt-8 pt-6\" style={{ borderTop: '1px solid var(--color-border)' }}>\n";
t += "            <Link to=\"/register\" className=\"button primary px-6 py-2.5 font-semibold\">Start your journey</Link>\n";
t += "          </div>\n";
t += "        </main>\n";
t += "      </Layout>\n";
t += "    );\n";
t += "  }\n";
fs.appendFileSync(f, '\n' + t, 'utf8');
console.log('Blog.jsx part 2a done', t.length);

let u = '';
u += "  return (\n";
u += "    <Layout>\n";
u += "      <main>\n";
u += "        <section style={{ padding: 'clamp(2.5rem,5vw,4rem) 1.5rem', textAlign: 'center', maxWidth: '700px', margin: '0 auto' }}>\n";
u += "          <h1 style={{ fontSize: 'clamp(1.75rem,4vw,2.75rem)', fontWeight: 700, color: 'var(--color-ink)', marginBottom: '0.75rem' }}>Guidance for your journey</h1>\n";
u += "          <p style={{ color: 'var(--color-ink-secondary)', fontSize: '1.0625rem' }}>Thoughtful articles on intentional matchmaking.</p>\n";
u += "        </section>\n";
u += "        <section style={{ maxWidth: '1200px', margin: '0 auto', padding: '0 1.5rem 4rem' }}>\n";
u += "          <div className=\"flex gap-2 mb-6 overflow-x-auto pb-2\">\n";
u += "            {categories.map(cat => (<button key={cat} onClick={() => setActiveCategory(cat)} className={'px-4 py-2 rounded-xl text-sm font-medium whitespace-nowrap ' + (activeCategory === cat ? 'text-white' : '')} style={activeCategory === cat ? { background: 'var(--color-primary)' } : { background: 'var(--color-elevated)', border: '1px solid var(--color-border)', color: 'var(--color-ink-secondary)' }}>{cat}</button>))}\n";
u += "          </div>\n";
u += "          <div className=\"grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6\">\n";
u += "            {filtered.map((article) => (\n";
u += "              <article key={article.id} className=\"group rounded-2xl overflow-hidden shadow-sm hover:shadow-xl hover:-translate-y-1 transition-all cursor-pointer\" style={{ background: 'var(--color-elevated)', border: '1px solid var(--color-border)' }} onClick={() => setReading(article)}>\n";
u += "                <div className=\"relative aspect-[16/10] overflow-hidden\">\n";
u += "                  <img src={article.image} alt={article.title} className=\"w-full h-full object-cover group-hover:scale-110 transition-transform duration-700\" loading=\"lazy\" />\n";
u += "                  {article.trending && (<div className=\"absolute top-3 left-3 flex items-center gap-1 text-[10px] font-bold text-white px-2 py-1 rounded-full\" style={{ background: 'var(--color-accent)' }}><TrendingUp className=\"w-3 h-3\" /> Trending</div>)}\n";
u += "                </div>\n";
u += "                <div className=\"p-5\">\n";
u += "                  <div className=\"flex items-center gap-2 mb-3\">\n";
u += "                    <span className=\"text-[11px] font-bold px-2.5 py-0.5 rounded-full\" style={{ color: 'var(--color-primary)', background: 'var(--color-primary-subtle)' }}>{article.category}</span>\n";
u += "                    <span className=\"text-[11px] flex items-center gap-1\" style={{ color: 'var(--color-ink-faint)' }}><Clock className=\"w-3 h-3\" /> {article.readTime}</span>\n";
u += "                  </div>\n";
u += "                  <h3 style={{ fontWeight: 600, color: 'var(--color-ink)', marginBottom: '0.5rem' }}>{article.title}</h3>\n";
u += "                  <p style={{ fontSize: '0.875rem', color: 'var(--color-ink-secondary)', lineHeight: 1.6, marginBottom: '1rem' }}>{article.excerpt}</p>\n";
u += "                  <div className=\"flex items-center justify-between pt-3\" style={{ borderTop: '1px solid var(--color-border)' }}>\n";
u += "                    <span style={{ fontSize: '0.75rem', color: 'var(--color-ink-faint)' }}>{article.date}</span>\n";
u += "                    <span className=\"flex items-center gap-1 text-xs font-semibold group-hover:gap-2 transition-all\" style={{ color: 'var(--color-primary)' }}>Read article <ArrowRight className=\"w-3 h-3\" /></span>\n";
u += "                  </div>\n";
u += "                </div>\n";
u += "              </article>\n";
u += "            ))}\n";
u += "          </div>\n";
u += "        </section>\n";
u += "      </main>\n";
u += "    </Layout>\n";
u += "  );\n";
u += "}\n";
fs.appendFileSync(f, '\n' + u, 'utf8');
console.log('Blog.jsx part 2b done', u.length);